name: Danger
on:
  pull_request:

jobs:
  Danger:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        run: brew install Danger JS 
          swift run danger-swift ci 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    

