name: Swift

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_14.0.1.app"
      - name: Build
        run: swift build
        - name: Danger
uses: danger/swift@3.16.0
